name = "splade_cocondenser_msmarco"
title = "Seismic on Splade Cocondenser embeddings of MS MARCO"
description = "Seismic on Splade Cocondenser embeddings of MS MARCO for the Table 1 (row 5) on SIGIR 2024 paper"
dataset = "Splade cocondenser on MS-MARCO"

[settings]
k = 10
n-runs = 1
build = true
metric = "RR@10"

[folder]
data = "/pscratch/sd/d/dhaura/datasets/SpKNN/seismic/experiments/sparse_datasets/msmarco_v1_passage/cocondenser/data"
index = "/pscratch/sd/d/dhaura/datasets/SpKNN/seismic/experiments/sparse_datasets/msmarco_v1_passage/cocondenser/indexes"
qrels_path = "/pscratch/sd/d/dhaura/datasets/SpKNN/seismic/experiments/sparse_datasets/msmarco_v1_passage/qrels.dev.small.tsv"
experiment = "."

[filename]
dataset = "documents.bin"
queries = "queries.bin"
groundtruth = "groundtruth.tsv"
doc_ids = "doc_ids.npy"
query_ids = "queries_ids.npy"
index = "sigir_2024_splade_cocondenser"

[indexing_parameters]
n-postings = 4000
centroid-fraction = 0.1
summary-energy = 0.4
knn = 0
clustering-algorithm = "random-kmeans"
kmeans-doc-cut = 15
kmeans-pruning-factor = 0.005

[query.recall_90]
query-cut = 3
heap-factor = 0.9

[query.recall_91]
query-cut = 4
heap-factor = 0.9

[query.recall_92]
query-cut = 4
heap-factor = 0.9

[query.recall_93]
query-cut = 5
heap-factor = 0.9

[query.recall_94]
query-cut = 8
heap-factor = 0.9

[query.recall_95]
query-cut = 5
heap-factor = 0.8

[query.recall_96]
query-cut = 6
heap-factor = 0.8

[query.recall_97]
query-cut = 6
heap-factor = 0.7
